<?php

/**
 * @file
 */

 /**
 * Implements hook_mail().
 */
function custom_contact_us_mail($key, &$message, $params) {
    /*$options = array(
      'langcode' => $message['langcode'],
    );*/
    $sitename =  \Drupal::config('system.site')->get('name');
    switch ($key) 
    {
        case 'contact_us':
         $message['from'] = \Drupal::config('system.site')->get('mail');
         $message['subject'] = t('Contact Us '.$sitename);
         $message['body'][] = $params['message'];
         $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed';
         break;
   }
}